import 'package:first_app/PestsAndInsects.dart';
import 'package:flutter/material.dart';

class Find extends StatelessWidget {
  Map<dynamic, dynamic> mp = {
    'Rice Case Worm':
        'The rice caseworm is commonly found in rice fields in low populations. It can build up and cause patches of severe defoliation that results in stunted growth and death of plants because of pesticide use, control practices, and ecological disruptions by weather.The rice plants can recover from the damage if there are no other defoliators present. However, maturity may be delayed for 7−10 days.Rice Case Worm Severity of damage Commonly found in irrigated and rain fed wetland rice fields with poor drainage. Damage may result in patches of severe defoliation, stunted growth and death of plants. Caseworm occurs regularly in low populations but sporadic outbreaks result in intense defoliation of plants causing severe loss in early vegetative stage. Rice plants can recover from the damage if there are no other defoliators present. However maturity may be delayed for 7 to 10 days.Integrated Pest Management • IPM is a knowledge-intensive sustainable approach for managing pests by combining compatible cultural, biological, chemical, and physical tools in a way that minimizes economic, health, and environmental risks with the help of pest scouts',
    'Stackburn of Rice':
        'This Stackburn fungus causes pre- and post-emergence seed rot (Srinivasaiah et al., 1984). After emergence, small dark-brown lesions may occur on the roots, the coleoptile or the early leaves. The parts of the seedling above lesions are blighted or the whole seedling dies (Padwick, 1950; Rush, 1992). Spots on later leaves, only occasionally seen, are oval to circular, 3-10 mm diameter and tan, later becoming grey to white with a narrow, dark-brown border (Padwick, 1950). Sheath rot in rice caused by T. padwickii, among other fungi, was reported for the first time by Naeimi et al. (2003) in northern Iran. In the "stackburn" phase of the disease, spots on glumes are pale brown to white or faintly pink or reddish-brown, usually with a darker border (Groth, 1992). Infected grain is dark coloured, chalky, brittle, and/or shriveled, with reduced viability (Lee, 1992b; Groth 1992). The small black sclerotia appear in the centre of lesions on all infected parts (Ou, 1985) and may be numerous in infected grains (Padwick, 1950).',
    'Aphids':
        'Aphids are soft-bodied insects that use their piercing sucking mouthparts to feed on plant sap. They usually occur in colonies on the undersides of tender terminal growth. Heavily-infested leaves can wilt or turn yellow because of excessive sap removal. While the plant may look bad, aphid feeding generally will not seriously harm healthy, established trees and shrubs.However, some plants are very sensitive to feeding by certain aphid species. Saliva injected into plants by these aphids may cause leaves to pucker or to become severely distorted, even if only a few aphids are present. Also, aphid feeding on flower buds and fruit can cause malformed flowers or fruit.Aphids produce large amounts of a sugary liquid waste called "honeydew". The honeydew that drops from these insects can spot the windows and finish of cars parked under infested trees. A fungus called sooty mold can grow on honeydew deposits that accumulate on leaves and branches, turning them black. The appearance of sooty mold on plants may be the first time that an aphid infestation is noticed. The drops can attract other insects such as ants, that will feed on the sticky deposits. ',
    'Whitebacked Planthopper':
        'A planthopper is any insect in the infraorder Fulgoromorpha, in the suborder Auchenorrhyncha, and exceeding 12,500 described species worldwide. The name comes from their remarkable resemblance to leaves and other plants of their environment and from the fact that they often "hop" for quick transportation in a similar way to that of grasshoppers. However, planthoppers generally walk very slowly. Distributed worldwide, all members of this group are plant-feeders, though surprisingly few are considered pests. The infraorder contains only a single superfamily, Fulgoroidea. Fulgoroids are most reliably distinguished from the other Auchenorrhyncha by two features; the bifurcate ("Y"-shaped) anal vein in the forewing, and the thickened, three-segmented antennae, with a generally round or egg-shaped second segment (pedicel) that bears a fine filamentous arista.',
    'Slugs and Snails':
        'While slugs and snails are common garden pests, they have little connection to garden insects. In the animal kingdom, these creatures belong to a category known as mollusks, the same group that includes octopuses and oysters. Slugs and snails are classified as gastropods, with “gastro" meaning stomach and “pod" meaning foot. The name sums up their anatomy well. Voracious eaters, they slide along on a muscular foot, eating plants and creating slimy mucus as they go.One visible difference between these closely related pests is that snails have hard, protective, external shells. Some slugs have soft internal shells or prominent mantles, while others have nothing at all. Both slugs and snails have two upper tentacles that protrude from their foreheads. Used for sight and smell, they carry eyes on the tips. Shorter, lower tentacles extending down from their heads are used for touch and taste.',
    'Red Rot':
        'This is one of the most severe of the known diseases of sugarcane. It was first described from Java by Went in 1893. It is widely distributed throughout the sugar­cane-growing countries of the world, and in fact it is extremely doubtful if there are any sugarcane-growing areas where it does not exist, although it may be much more destructive in some places than others.The disease was very widespread and virulent in North Behar and Eastern part of the United Provinces during 1939 and 1942. It was so destructive that it almost whipped out the sugarcane plantations in those areas.The first external evidences of disease are the drooping, withering, and finally yellowing of the upper leaves. This is followed by a similar wilting of the entire crown, and finally the entire plant shows indications of disease and dies. When not severe, the eyes frequently die and blacken and the dead areas extend out from the nodes.',
    'Wilt Disease':
        'A wilt disease is any number of diseases that affect the vascular system of plants. Attacks by fungi, bacteria, and nematodes can cause rapid killing of plants, large tree branches or even entire trees.Wilt diseases in woody plants tend to fall into two major categories, those that start with the branches and those that start with the roots. Those that start with the branches most often start with pathogens that feed on the leaves or bark, those that start with the roots start with wounding or direct entry by the pathogen into the roots, some are spread from one plant to another by way of root grafts.The fungal pathogen Fusarium sacchari causes wilt in sugarcane stalks and severely affects cane production and productivity in the crop. Many commercial varieties were lost due to their severity to the disease',
    'Bacterial Leaf Blight':
        'Bacterial blight is caused by Xanthomonas oryzae pv. oryzae.It causes wilting of seedlings and yellowing and drying of leaves.The disease is most likely to develop in areas that have weeds and stubbles of infected plants. It can occur in both tropical and temperate environments, particularly in irrigated and rainfed lowland areas. In general, the disease favors temperatures at 25−34°C, with relative humidity above 70%.It is commonly observed when strong winds and continuous heavy rains occur, allowing the disease-causing bacteria to easily spread through ooze droplets on lesions of infected plants.Bacterial blight can be severe in susceptible rice varieties under high nitrogen fertilization.',
    'Grassy Shoot':
        'The grassy shoot disease (GSD) of sugarcane occurs in most of the Asian countries, affecting sugarcane production to a considerable level. The disease is caused by grassy shoot I* phytoplasmas. In India the disease occurs in all the sugarcane arowing states.Symptoms caused by sugarcane grassy shoot disease. (a) Proliferation of chlorotic tillers at the base of a susceptible variety; (b) bud sprouting in SCGS infected canes stalks; (c) grassy shoot appearance in SCGS infected clumps. Disease was first observed near Belapur in the Ahmednagar district of Maharashtra in 1949(Chona, 1958) but now it has been recorded in all sugarcane growing states of India. ',
    'Yellow Stripe Rust':
        'Stripe rust (Puccinia striiformis f. sp. tritici) is an important disease of wheat (Triticum aestivum L.), especially in cool climates. Evidence of increased aggressiveness of the disease in the United States has been reported recently. Stripe rust is an emerging disease in the state of Georgia and has been more prevalent in the southern part of the state since 2003.Rusts are the most economically important group of wheat diseases. More than  billion is lost to cereal rusts (leaf rust, stem rust and stripe rust) worldwide each year. The capacity of rusts to develop into widespread epidemics is well documented. Rusts have complex life cycles that involve alternate hosts and several spores stages. Adding to this complexity are the numerous “physiological races” separable by patterns of pathogenicity and virulence on differential hosts. New races continually surface due to the rusts’ ability to mutate and sexually recombine.',
    'Powdery Mildew Of Cereals':
        'Powdery mildew, caused by the fungus Blumeria graminis, is one of the most common and damaging foliar diseases in wheat. Powdery mildew exists almost everywhere wheat is grown. As an obligate parasite, the fungus grows only on living tissue.Powdery mildew is particularly a problem in regions with high nitrogen fertilization and high stand densities. Cool, moist weather conditions with high relative humidity – 97 to 100 percent – enhance germination of the fungal infection. Optimum temperatures for development of powdery mildew are 59 to 70 degrees F, typically making it the first leaf disease of the season. When temperatures climb above 77 degrees F, powdery mildew begins to deteriorate. In much of the Midwest growing regions, powdery mildew in wheat occurs from April to July, but it can infect newly emerged wheat in the fall.',
    'Root and Foot Rot':
        'Common root and foot rot occurs in all wheat production areas of the U.S. and Canada. The pathogen (Bipolaris sorokiniana) has a wide host range and also causes a foliar disease known as spot blotch. Symptoms include dark, chocolate brown to black lesions on the coleoptile, stem, roots, and/or subcrown internode (the area above the seed to the soil line). Heavily diseased roots result in stunting and poor tiller and root development. Early season infections can result in poor stand. Premature ripening may occur resulting in shrunken kernels and, in some cases, sterile spikes. Spot blotch symptoms first appear on lower leaves and progress upwards as conditions permit. Lesions are oblong and brown with a dark brown center. Symptoms can be observed from tillering stages through ripening.',
    'Black Mould':
        'ust prior to and during wheat harvest each year, the Plant Disease Diagnostic Laboratories at Princeton and Lexington receive many samples with questions about severe head molding. This condition is known as black or sooty head mold. Sooty molds are caused by a large number of weakly parasitic and saprophytic fungi, especially species of Cladosporium and Alternaria. Affected heads exhibit extensive dark, olive-green, and black discoloration; this discoloration gives the heads a very weathered appearance.Sooty mold fungi colonize wheat heads when wet, humid weather occurs during the latter stages of grain development and crop maturation. Molding is frequently most severe when harvest is delayed. In addition, heads that are shaded, weakened, undersized, or prematurely ripe are frequently affected by sooty molds. Head molding is also prevalent when plants are deficient in nutrients, lodged, or damaged by insects or other diseases. Severe sooty mold, thus, is a red flag that other production problems may also be affecting the crop. However, this is not always the case as many high yielding crops ca be affected by sooty mold in any given year.',
    'White Grub':
        'White grubs are white to cream-colored, C-shaped with brown sclerotized head and shiny transparent tail section. Fully grown larvae are about 1.5 in (38 mm) long if straightened out. All white grubs have three larval development stages (instars).True white grubs are distinguishable from other white grubs by two conspicuous parallel rows of stiff hairs on the tail end that are zipper-like in appearance. Annual white grubs possess the scattered hairs on the same location but lack the parallel rows of stiff hairs. The white grubs of Popilia beetles possess two rows of spines in inverted "V" pattern on the underside of the abdominal segment.White grubs live underground and feed on plant roots. While larval damage is typically associated with grasses, white grubs also feed on corn roots. Feeding may cause stunting, nutritional deficiencies and stand loss. Corn with severely pruned roots appear stunted and easy to uproot. The larvae, particularly older grubs, can feed aggressively and easily move from root to root within the row. ',
    'Termites':
        'Termites are known as "silent destroyers" because of their ability to chew through wood, flooring and even wallpaper undetected. There are about 2,000 known termite species in the world. Each year, termites cause more than  billion in property damage.Termite, (order Isoptera), any of a group of cellulose-eating insects, the social system of which shows remarkable parallels with those of ants and bees, although it has evolved independently. Even though termites are not closely related to ants, they are sometimes referred to as white ants. Phylogenetic studies have shown that the closest relative to the termite is the cockroach; for this reason termites are sometimes placed in the order Dictyoptera, which also contains the mantids.',
    'Wireworms':
        'Wireworms are the larvae of many species in several genera called click beetles. Wireworms cause the damage not the adult click beetles. Since every geographic location has its own set of species, to know which wireworms are causing damage to potato, it is necessary to trap them and identify those in the potato field. An infested field will remain infested for three to six years and planting there should be avoided.Wireworms, the larvae of click beetles, damage potato by feeding primarily on tubers. The damage appears as straight, round holes with smooth walls. It is not clear whether the wireworm feeding is due to a search for shelter or due to thirst and not actually eating. Early in the season around planting, wireworms may drill into seed tubers or seed-pieces thereby weakening them possibly resulting in secondary infection especially by soft rot, in reduced stands and in weakened young plants. Wireworms also can feed on young sprouts with the same results. During the season, although not common, wireworms could damage roots and underground stem. For potato, the major damage is later in the season when tubers are maturing after bulking.',
    'Root Rot Of Cotton':
        'This fungal disease is also known as Phymatotrichum root rot, Texas root rot and Ozonium root rot. It is caused by one of the most destructive fungal plant disease organisms, Phymatotrichum omnivorum, that can attack more than 2,000 species of plants. However, monocotyledonous plants (grasses, etc.) have field resistance. In Texas, the disease is economically important in cotton, ornamentals and fruit, nut and shade trees. The fungus is prevalent in calcareous clay loam soils with a pH range of 7.0 to 8.5 and in areas with high summer temperatures. Therefore, the disease is limited to the Southwestern United States.ymptoms are most likely to occur from June through September when soil temperatures reach 28 °C (82 °F). The first symptoms are slight yellowing or bronzing of the leaves. The upper-most leaves wilt within 24 to 48 hours after bronzing, followed by wilting of the lower leaves within 72 hours. Permanent wilt occurs by the third day, followed by death. The leaves remain firmly attached to the plant. Affected plants die suddenly, often after excellent growth. Trees and shrubs may die more slowly.',
    'Bacterial Blight':
        'Brown spots on the margins of the cotyledons characterize plants infected early in the growing season. Young plants may be stunted and if the infection reaches the growing point, they may die. Symptoms in later growth stages include angular lesions, which begin as small yellow to brown spots on the leaves. The centers of the spots will turn a dark reddish-brown and dry out. A yellowish-green "halo" will appear around the edge of water soaked tissue that surrounds the lesions. Eventually the lesions will fall out of the leaf and the foliage will appear ragged. Generally young leaves are most susceptible to blight infection. Lesions can also occur on the pods causing the seeds to become shriveled and discolored. However, seeds usually do not show symptoms.Development of bacterial blight is promoted by cool, wet weather (70 – 80°F). Infection can occur early but is most common at mid season and continues until hot and dry weather limits development. Disease outbreaks often follow windy, rainstorms.',
    'Cotton Leafhopper Jassids':
        'They are small insects (1-3 mm long), green in colour with slender tapered bodies. Leafhoppers are very mobile. The adults hop away when disturbed. Nymphs resemble adults, but have no wings, and run sideways when disturbed. The eggs are inserted in the leaf tissue on the underside of leaflets. They feed mainly on the underside of eggplant leaves, causing small yellow patches on leaves. Infested leaves curl upwards along the margin. Under heavy attack, leaves turn yellow and then brown and dry, giving a burned appearance. Fruit setting may be very low. Leafhoppers multiply rapidly during dry spells and can cause extensive damage.Both nymphs and adults suck the sap from the under surface of leaves, tender leaves turn yellow, leaf margins curl downwards and reddening sets in. In the case of severe infestation leaves get a bronze or brick red colour which is typical “hopper burn”. Crop growth retarded.',
    'Leaf Spot':
        'There are many leaf spot diseases that occur on a wide range of native and ornamental trees and shrubs. Many leaf spot diseases have similar biology and therefore very similar management options.Information about some of these diseases is included below along with management information applicable to all leaf spot diseases of shade trees and shrubs.Fungicides are not necessary unless a tree has lost all of its leaves several years in a row.A leaf spot is a limited, discoloured, diseased area of a leaf that is caused by fungal, bacterial or viral plant diseases, or by injuries from nematodes, insects, environmental factors, toxicity or herbicides. These discoloured spots or lesions often have a centre of necrosis or cell death.Leaf spots are a type of plant disease that are usually caused by pathogens and sometimes other cases such as herbicide injuries.[3] Leaf spots can vary in size, shapes and colours depending on the age and type of the cause or pathogen.',
    'Damping of Seedlings':
        'Seedlings infected by damping off rarely survive to produce a vigorous plant. Quite often a large section or an entire tray of seedlings is killed.Once plants have mature leaves and a well developed root system, they are better able to naturally resist the fungus or mold that causes damping off. There is a critical period of growth between planting and maturity when special care needs to be taken to protect sensitive seedlings.A wide variety of vegetables and flowers can be affected by damping off. Young leaves, roots and stems of newly emerged seedlings are highly susceptible to infection. Under certain environmental conditions, damping off pathogens can cause root rot or crown rot in mature plants.'
  };
  String index1, index2, index3;
  Find(this.index1, this.index2, this.index3);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        toolbarHeight: 200.0,
        flexibleSpace: Container(
          decoration: BoxDecoration(
              image:
                  DecorationImage(fit: BoxFit.fill, image: AssetImage(index3))),
        ),
        automaticallyImplyLeading: false,
        brightness: Brightness.dark,
      ),
      body: ListView(
        children: <Widget>[
          Container(
            padding: EdgeInsets.only(left: 10.0),
            child: Text(
              '\n$index1',
              style: TextStyle(fontSize: 25.0, fontWeight: FontWeight.bold),
            ),
          ),
          Container(
            padding: EdgeInsets.only(left: 10.0),
            child: Text(
              '$index2\n\n',
              style: TextStyle(fontSize: 17.0),
            ),
          ),
          Container(
            padding: EdgeInsets.all(5.0),
            child: Text(
              '${mp[index1]}',
              style: TextStyle(fontSize: 15.0),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        label: Text(
          'Back',
        ),
        icon: Icon(Icons.navigate_before),
        backgroundColor: Color.fromRGBO(64, 64, 64, 1),
        onPressed: () {
          Navigator.of(context).pop(
              MaterialPageRoute(builder: (BuildContext context) => Pests(0)));
        },
      ),
    );
  }
}
